crunner: Rewrite for performance and clarity
* crunner: Rewrite for performance and clarity

- Fixup nested if statements.
- Switch to case expressions for some conditions.
- Switch to for loop instead of while loop for argument parsing.
- Fix shellcheck warnings.
- Simplify logic of code.
- Expand usage of compilers.
- Switch to arg-based usage.

Co-authored-by: PeroSar <perosar1111@gmail.com>
Signed-off-by: PeroSar <perosar1111@gmail.com>
Signed-off-by: Cyber Knight <cyberknight755@gmail.com>

* crunner: Format with 4 spaces

- Use `shfmt -w -i 4 crunner` to do it.

Signed-off-by: Cyber Knight <cyberknight755@gmail.com>

Co-authored-by: PeroSar <perosar1111@gmail.com>

diff --git a/crunner b/crunner
--- a/crunner
+++ b/crunner
@@ -1,92 +1,100 @@
 #!/bin/bash
+# shellcheck disable=SC2086
 
 red=$(tput setaf 1)
 blue=$(tput setaf 4)
 white=$(tput setaf 7)
 
 USAGE="./$(basename "$0") file -- compiles and executes the executable
-./$(basename "$0") d file -- compiles the file in debug mode and executes it
+./$(basename "$0") --cc=<compiler> file -- compiles the *.c file with specified compiler
+./$(basename "$0") --cxx=<compiler> file -- compiles the *.cpp file with specified compiler
+./$(basename "$0") --debug file -- compiles the file in debug mode and executes it
 ./$(basename "$0") clean -- removes temp and debug files"
 
-while getopts h input
-do
-case "${input}"
-in
-h) echo "${USAGE}" && exit 0 ;;
-*) exit 0 ;;
-esac
-done
-
-_ERROR_UFT_C_(){
-	ERROR="$(echo "${white}This file type can't be compiled")"
-
-   	echo "${red}ERROR:" "$ERROR"
+_ERROR_UFT_C_() {
+    echo "${red}ERROR:" "${white}This file type can't be compiled or file does not exist!"
 }
 
-_ERROR_UFT_D_(){
-	ERROR="$(echo "${white}This file type doesn't support compilation in debug mode")"
-
-   	echo "${red}ERROR:" "$ERROR"
+_EXIT_() {
+    echo "${blue}Exitting crunner..."
+    exit 0
 }
 
-_EXIT_(){
-   	echo "${blue}Exitting crunner.."
-	exit 0;
+run() {
+
+    CFLAGS="-Wall"
+    if [ "${DEBUG}" = true ]; then
+        CFLAGS+=" -g -O0"
+    else
+        CFLAGS+=" -s -w -O3"
+    fi
+
+    if [[ "${FILE#*.}" == c ]]; then
+        "${CC:=gcc}" ${CFLAGS} ${FILE} -o "${FILE%%.*}.out"
+        ./"${FILE%%.*}.out"
+    elif [[ "${FILE#*.}" == cpp ]]; then
+        "${CXX:=g++}" ${CFLAGS} ${FILE} -o "${FILE%%.*}.out"
+        ./"${FILE%%.*}.out"
+    else
+        _ERROR_UFT_C_
+        _EXIT_
+    fi
 }
 
-run(){
-	if [[ "${FILE#*.}" == c ]]; then
-    	gcc -Wall "$FILE" -o "${FILE%%.*}.out"
-    	./"${FILE%%.*}.out"
-	elif [[ "${FILE#*.}" == cpp ]]; then
-    	g++ -Wall "$FILE" -o "${FILE%%.*}.out"
-    	./"${FILE%%.*}.out"
-	else
-		_ERROR_UFT_C_
-		_EXIT_
-	fi
-}
-
-run_debug(){
-	if [[ "${FILE#*.}" == c ]]; then
-    	gcc -Wall -g -O0 "$FILE" -o "${FILE%%.*}.out"
-    	./"${FILE%%.*}.out"
-	elif [[ "${FILE#*.}" == cpp ]]; then
-    	g++ -Wall -g -O0 "$FILE" -o "${FILE%%.*}.out"
-    	./"${FILE%%.*}.out"
-	else
-		_ERROR_UFT_D_
-		_EXIT_
-	fi
-}
-
-FILE_LOCATION="$1"
-
-if [[ "$1" == "clean" ]]; then
-	find . -type d -name "*.dSYM" -exec rm -rf {} \; 2>/dev/null	
-	rm -rf tempCodeRunnerFile.c	
-elif [[ "$1" == "d" ]]; then
-	FILE_LOCATION="$2"
-	
-	if [[ "$FILE_LOCATION" != */* ]]; then
-		FILE="$FILE_LOCATION"
-
-		run_debug
-	else
-		LOCATION="${FILE_LOCATION%/*}"
-		FILE="${FILE_LOCATION##*/}"
-
-		cd "$LOCATION" || exit
-		run_debug
-	fi
-elif [[ "$FILE_LOCATION" != */* ]]; then
-	FILE="$FILE_LOCATION"
-
-	run
-else
-	LOCATION="${FILE_LOCATION%/*}"
-	FILE="${FILE_LOCATION##*/}"
-
-	cd "$LOCATION" || exit
-	run
+if [[ -z $* ]]; then
+    echo "${USAGE}" && exit 0
 fi
+
+for arg in "$@"; do
+    case "${arg}" in
+
+    "-h" | "--help")
+        echo "${USAGE}" && exit 0
+        ;;
+    *".c" | *".cpp")
+        FILE_LOCATION="${arg}"
+        if [ ! -f $FILE_LOCATION ]; then
+            _ERROR_UFT_C_
+            _EXIT_
+        fi
+        if [[ "${FILE_LOCATION}" != */* ]]; then
+            FILE="${FILE_LOCATION}"
+            run
+        else
+            LOCATION="${FILE_LOCATION%/*}"
+            FILE="${FILE_LOCATION##*/}"
+            cd "${LOCATION}" || exit 1
+            run
+        fi
+        ;;
+    "--cc="*)
+        c="${arg#*=}"
+        if [[ -z "$c" ]]; then
+            echo "Use --cc=gcc/clang"
+        else
+            export CC="${c}"
+            shift
+        fi
+        ;;
+    "--cxx="*)
+        cx="${arg#*=}"
+        if [[ -z "$cx" ]]; then
+            echo "Use --cxx=g++/clang++"
+        else
+            export CXX="${cx}"
+            shift
+        fi
+        ;;
+    "clean")
+        find . -type d -name "*.dSYM" -exec rm -rf {} \; 2>/dev/null
+        rm -rf tempCodeRunnerFile.c
+        ;;
+    "--debug")
+        DEBUG=true
+        ;;
+    *)
+        _ERROR_UFT_C_
+        _EXIT_
+        ;;
+    esac
+done
