minor syntax fixes

diff --git a/crunner b/crunner
--- a/crunner
+++ b/crunner
@@ -3,7 +3,6 @@
 ##########################################################
 #              crunner - code-runner                     #
 #                                                        #
-#  Compile and run codes written in supported langs.     #
 #  Automate the process for compiling and executing      #
 #  your code in multiple langs using singe command.      #
 #                                                        #
@@ -41,141 +40,141 @@ run ${red}clean-exe${white}  ${yellow}:${white} deletes all executable files wit
 run ${red}clean${white}      ${yellow}:${white} removes debug folder, .out and temp files"
 
 _ERROR_UFTC_() {
-    echo "${red}ERROR: ${white}This file type can't be compiled or the file does not exist!"
+	echo "${red}ERROR: ${white}This file type can't be compiled or the file does not exist!"
 }
 
 _EXIT_() {
-    echo "${blue}Exiting crunner..."
-    exit 0
+	echo "${blue}Exiting crunner..."
+	exit 0
 }
 
 ## choosing either gdb or lldb according to which one is present, if both are then gdb is prioritised
 default_debugger() {
 
-    if [[ -n $(command -v gdb) ]]; then
-    	: "${debugger:=gdb}"
-    elif [[ -n $(command -v lldb) ]]; then
-    	: "${debugger:=lldb}"
-    fi
+	if [[ -n $(command -v gdb) ]]; then
+		: "${debugger:=gdb}"
+	elif [[ -n $(command -v lldb) ]]; then
+		: "${debugger:=lldb}"
+	fi
 }
 
 rclean_exe() {
-    find . -type f -perm +111 -exec rm -rf {} \; 2>/dev/null
+	find . -type f -perm +111 -exec rm -rf {} \; 2>/dev/null
 }
 
 clean_exe() {
-    find . -type f -maxdepth 1 -perm +111 -exec rm -rf {} \; 2>/dev/null
+	find . -type f -maxdepth 1 -perm +111 -exec rm -rf {} \; 2>/dev/null
 }
 
 clean() {
 
-    find . -type d -name "*.dSYM" -exec rm -rf {} \; 2>/dev/null
-    find . -type f -name "*.out" -exec rm -rf {} \; 2>/dev/null
-    find . -type f -name "tempCodeRunnerFile.*" -exec rm -rf {} \; 2>/dev/null
+	find . -type d -name "*.dSYM" -exec rm -rf {} \; 2>/dev/null
+	find . -type f -name "*.out" -exec rm -rf {} \; 2>/dev/null
+	find . -type f -name "tempCodeRunnerFile.*" -exec rm -rf {} \; 2>/dev/null
 }
 
 run() {
 
-    set -m
-    default_debugger
+	set -m
+	default_debugger
 
-    CFLAGS="-Wall"
-    if [[ $DEBUG == true ]]; then
-        CFLAGS+=" -g -O0"
-    else
-        CFLAGS+=" -s -w -O3"
-    fi
-
-    if [[ ${FILE#*.} == c ]]; then
-        "${CC:=gcc}" "$CFLAGS" "$FILE" -o "${FILE%%.*}.out"
-
-        if [[ $DEBUG == true ]]; then
-	        $debugger "${FILE%%.*}.out"
-	        rm -rf ./"${FILE%%.*}.out.dSYM"
-        else
-            ./"${FILE%%.*}.out"
-        fi
-        rm -rf ./"${FILE%%.*}.out"
-
-    elif [[ ${FILE#*.} == cpp ]]; then
-        "${CXX:=g++}" "$CFLAGS" "$FILE" -o "${FILE%%.*}.out"
-
+	CFLAGS="-Wall"
 	if [[ $DEBUG == true ]]; then
-	    $debugger "${FILE%%.*}.out"
-	    rm -rf ./"${FILE%%.*}.out.dSYM"
+		CFLAGS+=" -g -O0"
 	else
-        ./"${FILE%%.*}.out"
+		CFLAGS+=" -s -w -O3"
 	fi
-        rm -rf ./"${FILE%%.*}.out"
-    else
-        _ERROR_UFTC_
-        _EXIT_
-    fi
+
+	if [[ ${FILE#*.} == c ]]; then
+		"${CC:=gcc}" "$CFLAGS" "$FILE" -o "${FILE%%.*}.out"
+
+		if [[ $DEBUG == true ]]; then
+			"$debugger" "${FILE%%.*}.out"
+			rm -rf ./"${FILE%%.*}.out.dSYM"
+		else
+			./"${FILE%%.*}.out"
+		fi
+
+		rm -rf ./"${FILE%%.*}.out"
+	elif [[ ${FILE#*.} == cpp ]]; then
+		"${CXX:=g++}" "$CFLAGS" "$FILE" -o "${FILE%%.*}.out"
+
+		if [[ $DEBUG == true ]]; then
+			"$debugger" "${FILE%%.*}.out"
+			rm -rf ./"${FILE%%.*}.out.dSYM"
+		else
+			./"${FILE%%.*}.out"
+		fi
+
+		rm -rf ./"${FILE%%.*}.out"
+	else
+		_ERROR_UFTC_
+		_EXIT_
+	fi
 }
 
 if [[ -z $* ]]; then
-    echo "$USAGE" && exit 0
+	echo "$USAGE" && exit 0
 fi
 
 for arg in "$@"; do
-    case $arg in
+	case $arg in
 
-    "-h" | "--help")
-        echo "$USAGE" && exit 0
-        ;;
-    *".c" | *".cpp")
-        FILE_LOCATION=$arg
-        if [[ ! -f $FILE_LOCATION ]]; then
-            _ERROR_UFTC_
-            _EXIT_
-        fi
+	"-h" | "--help")
+		echo "$USAGE" && exit 0
+		;;
+	*".c" | *".cpp")
+		FILE_LOCATION=$arg
+		if [[ ! -f $FILE_LOCATION ]]; then
+			_ERROR_UFTC_
+			_EXIT_
+		fi
 
-        if [[ $FILE_LOCATION != */* ]]; then
-            FILE=$FILE_LOCATION
-            run
-        else
-            LOCATION=${FILE_LOCATION%/*}
-            FILE=${FILE_LOCATION##*/}
-            cd "$LOCATION" || exit 1
-            run
-        fi
-        ;;
-    "--cc="* | "-c="*)
-        c=${arg#*=}
-        if [[ -z $c ]]; then
-            echo "Use --cc=gcc/clang"
-            echo "OR"
-            echo "Use -c=gcc/clang"
-        else
-            export CC=$c
-            shift
-        fi
-        ;;
-    "--cxx="*)
-        cx=${arg#*=}
-        if [[ -z $cx ]]; then
-            echo "Use --cxx=g++/clang++"
-        else
-            export CXX=$cx
-            shift
-        fi
-        ;;
-    "clean")
-	    clean
-	    ;;
-    "clean-exe")
-	    clean_exe
-	    ;;
-    "rclean-exe")
-	    rclean_exe
-	    ;;
-    "--debug" | "d")
-        DEBUG=true
-        ;;
-    *)
-        _ERROR_UFTC_
-        _EXIT_
-        ;;
-    esac
+		if [[ $FILE_LOCATION != */* ]]; then
+			FILE=$FILE_LOCATION
+			run
+		else
+			LOCATION=${FILE_LOCATION%/*}
+			FILE=${FILE_LOCATION##*/}
+			cd "$LOCATION" || exit 1
+			run
+		fi
+		;;
+	"--cc="* | "-c="*)
+		c=${arg#*=}
+		if [[ -z $c ]]; then
+			echo "Use --cc=gcc/clang"
+			echo "OR"
+			echo "Use -c=gcc/clang"
+		else
+			export CC=$c
+			shift
+		fi
+		;;
+	"--cxx="*)
+		cx=${arg#*=}
+		if [[ -z $cx ]]; then
+			echo "Use --cxx=g++/clang++"
+		else
+			export CXX=$cx
+			shift
+		fi
+		;;
+	"clean")
+		clean
+		;;
+	"clean-exe")
+		clean_exe
+		;;
+	"rclean-exe")
+		rclean_exe
+		;;
+	"--debug" | "d")
+		DEBUG=true
+		;;
+	*)
+		_ERROR_UFTC_
+		_EXIT_
+		;;
+	esac
 done
-
