better error handling

diff --git a/run b/run
--- a/run
+++ b/run
@@ -43,15 +43,11 @@ ${blue}Clean Utility:${white}
   run ${red}clean${white}      ${yellow}:${white} removes debug folder, executables and temp files
 
 ${blue}Miscellaneous:${white}
-  run [${red}--list-langs${white}/${red}-ll${white}] ${yellow}:${white} lists all languages supported by current version of code-runner
-  run [${red}--version${white}/${red}-v${white}]     ${yellow}:${white} echoes the current version of code-runner"
-
-_ERROR_UFTC_() {
-	echo "${red}ERROR: ${white}This file type can't be compiled or the file does not exist!"
-}
+  run [${red}--list-langs${white}/${red}ll${white}] ${yellow}:${white} lists all languages supported by current version of code-runner
+  run [${red}--version${white}/${red}v${white}]     ${yellow}:${white} echoes the current version of code-runner"
 
 _EXIT_() {
-	echo "${blue}Exiting crunner..."
+	echo "${blue}Exiting code-runner"
 	exit 0
 }
 
@@ -84,6 +80,8 @@ run() {
 
 	set -m
 
+	# C[++] fam specifics
+	default_debugger
 	CFLAGS="-Wall"
 	if [[ $DEBUG == true ]]; then
 		CFLAGS+=" -g -O0"
@@ -92,7 +90,6 @@ run() {
 	fi
 
 	if [[ ${FILE#*.} == c ]]; then
-		default_debugger
 		"${CC:=gcc}" ${CFLAGS} "$FILE" -o "${FILE%%.*}.out"
 		if [[ $DEBUG == true ]]; then
 			"$debugger" "${FILE%%.*}.out"
@@ -105,7 +102,6 @@ run() {
 		fi
 
 	elif [[ ${FILE#*.} == cpp ]]; then
-		default_debugger
 		"${CXX:=g++}" ${CFLAGS} "$FILE" -o "${FILE%%.*}.out"
 		if [[ $DEBUG == true ]]; then
 			"$debugger" "${FILE%%.*}.out"
@@ -130,14 +126,12 @@ run() {
 				dpyv=2
 			fi
 			rm -rf "${FILE%%.*}.pyc" __pycache__
+		elif [[ $pyv == 3 ]]; then
+			py="python3"
+			dpyv=3
 		else 
-			if [[ $pyv == 3 ]]; then
-				py="python3"
-				dpyv=3
-			else 
-				py="python2"
-				dpyv=2
-			fi
+			py="python2"
+			dpyv=2
 		fi
 		echo "${yellow}>> Using python $dpyv${white}"
 		if [[ $COMPILE == true ]]; then
@@ -159,7 +153,6 @@ run() {
 		javac "$FILE"
 		JCF=$(find . -type f -name "*.class" -mmin -1 | cut -c 3-)
 		classFileCount=$(find . -type f -name "*.class" -mmin -1 | wc -l)
-
 		if [[ $COMPILE != true ]]; then
 			while [ "$classFileCount" -gt 0 ]
 			do
@@ -193,7 +186,7 @@ run() {
 			go run "$FILE"
 		fi
 		if [[ $PERSISTENT != true ]]; then
-			rm "${FILE%%.*}.out"
+			rm -rf "${FILE%%.*}.out"
 		fi
 		
 	elif [[ ${FILE#*.} == pl ]]; then
@@ -214,10 +207,6 @@ run() {
 		else
 			runghc "$FILE" 
 		fi
-
-	else
-		_ERROR_UFTC_
-		_EXIT_
 	fi
 }
 
@@ -231,8 +220,7 @@ for arg in "$@"; do
 	"-h" | "--help")
 		echo "$USAGE" && exit 0
 		;;
-
-	"ll" | "--list-langs")
+	"--list-langs" | "ll")
 		echo
 		echo "  ${cyan}Languages supported by the currently installed version of ${red}code-runner${cyan}:"
 		echo "    ${yellow}>>${white} C             ${cyan}[${white}with ${green}debug${white} support${cyan}]"
@@ -249,22 +237,8 @@ for arg in "$@"; do
 		echo "    ${yellow}>>${white} Haskell       ${cyan}[${white}with ${green}debug${white} support${cyan}]"
 		echo
 		;;
-
-	*".c" | *".cpp" | *".py" | *".rs" | *".java" | *".sh" | *".js" | *".go" | *".pl" | *".lua" | *".rb" | *".hs")
-		FILE_LOCATION=$arg
-		if [[ ! -f $FILE_LOCATION ]]; then
-			_ERROR_UFTC_
-			_EXIT_
-		fi
-		if [[ $FILE_LOCATION != */* ]]; then
-			FILE=$FILE_LOCATION
-			run
-		else
-			LOCATION=${FILE_LOCATION%/*}
-			FILE=${FILE_LOCATION##*/}
-			cd "$LOCATION" || exit 1
-			run
-		fi
+	"--version" | "v")
+		echo "${cyan}code-runner ${white}version : ${yellow}1.2.0${white}"
 		;;
 
 	"--cc="* | "-c="*)
@@ -318,11 +292,31 @@ for arg in "$@"; do
 	"rcexe")
 		rclean_exe
 		;;
-	"--version" | "-v")
-		echo "${cyan}code-runner ${white}version : ${yellow}1.2.0${white}"
+
+	*".c" | *".cpp" | *".py" | *".rs" | *".java" | *".sh" | *".js" | *".go" | *".pl" | *".lua" | *".rb" | *".hs")
+		FILE_LOCATION=$arg
+		if [[ ! -f $FILE_LOCATION ]]; then
+			echo "${red}ERROR: ${white}Specified file doesn't exist."
+			_EXIT_
+		fi
+		if [[ $FILE_LOCATION != */* ]]; then
+			FILE=$FILE_LOCATION
+			run
+		else
+			LOCATION=${FILE_LOCATION%/*}
+			FILE=${FILE_LOCATION##*/}
+			cd "$LOCATION" || exit 1
+			run
+		fi
+		;;
+	*.*)
+		echo "${red}ERROR: ${white}Usupported file-type specified.
+       To get a list of supported file-types use: ${green}run ll${white}"
+		_EXIT_
 		;;
 	*)
-		_ERROR_UFTC_
+		echo "${red}ERROR: ${white}Unknown argument specified.
+       To get a list of supported arguments use: ${green}run --help${white}"
 		_EXIT_
 		;;
 	esac
